ci: .

diff --git a/.github/actions/get-version/action.yml b/.github/actions/get-version/action.yml
--- a/.github/actions/get-version/action.yml
+++ b/.github/actions/get-version/action.yml
@@ -1,6 +1,10 @@
 name: 'Get Version'
 description: 'Get version from a project json version file'
 inputs:
+  pattern:
+    description: 'The regular expression pattern to match'
+    required: true
+
   version_file_path:
     description: 'Path to the json version file'
     required: true
@@ -13,6 +17,17 @@ runs:
       run: |
         echo "::set-output name=version::$(jq -r .version ${{ inputs.version_file_path }})"
 
+    - name: Verify version
+      shell: bash
+      run: |
+        if [[ "${{ steps.read_version.outputs.version }}" =~ ${{ inputs.pattern }} ]]; then
+          echo "Version is valid"
+        else
+          echo "Invalid version"
+          exit 1
+        fi
+
     - name: Set version as environment variable
       shell: bash
       run: echo "VERSION=${{ steps.read_version.outputs.version }}" >> $GITHUB_ENV
+
diff --git a/.github/workflows/docker-hub-stable.yml b/.github/workflows/docker-hub-stable.yml
--- a/.github/workflows/docker-hub-stable.yml
+++ b/.github/workflows/docker-hub-stable.yml
@@ -18,36 +18,27 @@ jobs:
       uses: ./.github/actions/get-version
       with:
         version_file_path: ./src/Atmosphere/version.json
+        pattern: '^[0-9]+\.[0-9]+\.[0-9]+$'
     
-    - name: Verify version
-      run: |
-        if [[ "${{ env.VERSION }}" =~ ^[0-9\.]+$ ]]; then
-          echo "Version is valid"
-        else
-          echo "Invalid version"
-          exit 1
-        fi
+    # - name: Verify if it's a stable version
+    #   run: |
+    #     if [[ "${{ env.VERSION }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+    #       echo "Version is valid"
+    #     else
+    #       echo "Invalid version"
+    #       exit 1
+    #     fi
+      
 
-    - name: Login to Docker Hub
-      uses: ./.github/actions/docker-hub
+    - name: Docker Build and Push
+      uses: ./.github/actions/docker-build-push
       with:
         docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
         docker_hub_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
-    
-    - name: Docker Build
-      uses: ./.github/actions/docker-build
-      with:
         docker_image: ${{ vars.DOCKER_IMAGE }}
-        channel_tag: latest
+        channel_tag: stable
         version_tag: ${{ env.VERSION }}
         docker_file_path: ./docker/Dockerfile
         source_directory: ./src
-    
-    - name: Docker Push
-      uses: ./.github/actions/docker-push
-      with:
-        docker_image: ${{ vars.DOCKER_IMAGE }}
-        channel_tag: latest
-        version_tag: ${{ env.VERSION }}
     
 
